# Generated by scripts/bump-cask.sh — do not edit here.
# Source: packaging/homebrew/etch.rb.tmpl in the etch repo.
cask "etch" do
  version "1.5.0"
  sha256 "f8398fc8968a4a5d4c09b0d3a9a048e707132dece70abbca2f41b6c5dbb1ecb6"

  url "https://download.makailabs.io/etch/Etch-#{version}.dmg",
      verified: "download.makailabs.io/etch/"
  name "Etch"
  desc "Local-first, keyboard-driven markdown note-taking app"
  homepage "https://etch.makailabs.io/"

  livecheck do
    url "https://download.makailabs.io/etch/updates/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # These three are one stanza group — Homebrew's StanzaGrouping cop
  # rejects blank lines between them, so the reasoning lives up here.
  #
  # auto_updates: Etch ships its own updater (tauri-plugin-updater,
  # pointed at the latest.json above), so Homebrew installs and then
  # steps aside. Without it, `brew upgrade` would reinstall over an app
  # that already updated itself — and it's what makes a late cask bump a
  # non-event rather than a user-facing problem.
  #
  # arch: `tauri build` runs on an arm64 host with no --target, so the
  # shipped binary is single-arch. Declaring it gives an Intel user a
  # clean refusal instead of an app that installs and won't launch.
  # Going universal later means dropping that line and adding a
  # darwin-x86_64 entry to latest.json — the updater keys on the arch it
  # was compiled for and has no "universal" key.
  #
  # macos: a bare symbol means ">= that version" for casks
  # (cask/dsl/depends_on.rb passes comparator: ">="); the ">= :ventura"
  # string form is deprecated. Mirrors the macOS 13+ floor the website
  # advertises.
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :ventura

  app "Etch.app"

  # zap only — a plain `brew uninstall` must leave every one of these in
  # place. vault-state/ under Application Support is the sidecar mirror
  # that recovers a vault whose .etch-state.json got shelved by a
  # syncing Dropbox client, so removing it on a routine uninstall would
  # throw away the safety net.
  #
  # Notes themselves live in vault folders the user chose, and possibly
  # in ~/Library/Mobile Documents/…/Etch/ under iCloud. Never list those
  # here: zap is aggressive by design and user data is not ours to trash.
  zap trash: [
    "~/Library/Application Support/io.makailabs.etch",
    "~/Library/Caches/io.makailabs.etch",
    "~/Library/HTTPStorages/io.makailabs.etch",
    "~/Library/Logs/io.makailabs.etch",
    "~/Library/Preferences/io.makailabs.etch.plist",
    "~/Library/Saved Application State/io.makailabs.etch.savedState",
    "~/Library/WebKit/io.makailabs.etch",
  ]
end
